# Generated by Django 5.2.18 on 2026-10-06 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        ("testcases", "0002_testcase_source_scenario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "domain_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed", "Confirmed"),
                            ("remediated", "Remediated"),
                            ("accepted", "Risk accepted"),
                            ("false_positive", "False positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("cvss_vector", models.CharField(blank=True, max_length=120)),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "affected",
                    models.TextField(
                        blank=True,
                        help_text="Affected hosts / URLs / assets, one per line.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                (
                    "references",
                    models.TextField(
                        blank=True, help_text="Links / CVEs, one per line."
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_test_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="testcases.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
