# Generated by Django 5.2.18 on 2026-10-06 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_key",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("pass", "Pass (no issue)"),
                            ("fail", "Fail (issue found)"),
                            ("na", "N/A"),
                            ("blocked", "Blocked"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_custom", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_test_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("domain_key", "category", "order", "id"),
            },
        ),
    ]
