# Generated by Django 5.2.18 on 2026-10-06 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("testcases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="source_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_test_cases",
                to="catalog.scenario",
            ),
        ),
    ]
