# Generated by Django 5.2.18 on 2026-10-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("testcases", "0002_testcase_source_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_cases",
                to="assets.function",
            ),
        ),
    ]
