# Generated by Django 5.2.18 on 2026-10-06 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "code",
                    models.SlugField(
                        help_text="Short reference, e.g. ACME-2026-01",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scoping", "Scoping"),
                            ("active", "Active"),
                            ("review", "In Review"),
                            ("delivered", "Delivered"),
                            ("closed", "Closed"),
                        ],
                        default="scoping",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagements",
                        to="clients.clientorg",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ScopeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ip", "IP / CIDR"),
                            ("host", "Hostname"),
                            ("url", "URL"),
                            ("ssid", "Wi-Fi SSID"),
                            ("ad_domain", "AD Domain"),
                            ("device", "Device / Asset"),
                            ("other", "Other"),
                        ],
                        default="ip",
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("in_scope", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_items",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ("-in_scope", "kind", "value"),
            },
        ),
        migrations.CreateModel(
            name="TeamAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement_role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("tester", "Tester"),
                            ("reviewer", "Reviewer"),
                        ],
                        default="tester",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("engagement", "engagement_role"),
                "unique_together": {("user", "engagement")},
            },
        ),
        migrations.AddField(
            model_name="engagement",
            name="members",
            field=models.ManyToManyField(
                related_name="engagements",
                through="engagements.TeamAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EngagementDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_key",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ("domain_key",),
                "unique_together": {("engagement", "domain_key")},
            },
        ),
    ]
