# Generated by Django 5.2.18 on 2026-10-08 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "primary_target",
                    models.CharField(
                        blank=True,
                        help_text="Main address/identifier (URL, IP, hostname, SSID).",
                        max_length=255,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("walkthrough", models.TextField(blank=True, help_text="Markdown.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ("asset_type", "name"),
                "unique_together": {("engagement", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'admin web login', 'domain user'",
                        max_length=160,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("hash", "Hash"),
                            ("token", "Token / key"),
                            ("ssh_key", "SSH key"),
                            ("other", "Other"),
                        ],
                        default="password",
                        max_length=20,
                    ),
                ),
                ("secret_encrypted", models.TextField(blank=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="FileArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("binary", "Binary"),
                            ("config", "Config"),
                            ("library", "Library / DLL"),
                            ("installer", "Installer"),
                            ("other", "Other"),
                        ],
                        default="binary",
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=500)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("protocol", models.CharField(blank=True, max_length=10)),
                ("name", models.CharField(blank=True, max_length=80)),
                ("product", models.CharField(blank=True, max_length=160)),
                ("version", models.CharField(blank=True, max_length=80)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ("port",),
            },
        ),
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functions",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
                "unique_together": {("asset", "name")},
            },
        ),
    ]
