# Generated by Django 5.2.18 on 2026-10-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("primary_contact_name", models.CharField(blank=True, max_length=160)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "client organization",
                "ordering": ("name",),
            },
        ),
    ]
