from django.test import TestCase
from django.urls import reverse

from apps.accounts.models import Role, User
from apps.clients.models import ClientOrg
from apps.engagements.models import Engagement, TeamAssignment

from .models import Page
from .render import render_markdown


class RenderTests(TestCase):
    def test_basic_markdown(self):
        html = render_markdown("# Title\n\n**bold** and `code`")
        self.assertIn("<h1>", html)
        self.assertIn("<strong>bold</strong>", html)
        self.assertIn("<code>code</code>", html)

    def test_strips_script_xss(self):
        html = render_markdown("hi <script>alert(1)</script> there")
        self.assertNotIn("<script>", html)
        self.assertNotIn("alert(1)", html)

    def test_strips_event_handler_and_js_href(self):
        html = render_markdown('<a href="javascript:alert(1)" onclick="x()">x</a>')
        self.assertNotIn("javascript:", html)
        self.assertNotIn("onclick", html)

    def test_tables_render(self):
        html = render_markdown("| a | b |\n| --- | --- |\n| 1 | 2 |")
        self.assertIn("<table>", html)


class PageModelTests(TestCase):
    def setUp(self):
        self.c = ClientOrg.objects.create(name="Acme")
        self.eng = Engagement.objects.create(client=self.c, title="T", code="A-1")

    def test_slug_autogenerated_and_unique(self):
        p1 = Page.objects.create(engagement=self.eng, title="Recon Notes")
        p2 = Page.objects.create(engagement=self.eng, title="Recon Notes")
        self.assertEqual(p1.slug, "recon-notes")
        self.assertNotEqual(p1.slug, p2.slug)

    def test_ancestors_order(self):
        root = Page.objects.create(engagement=self.eng, title="Root")
        mid = Page.objects.create(engagement=self.eng, title="Mid", parent=root)
        leaf = Page.objects.create(engagement=self.eng, title="Leaf", parent=mid)
        self.assertEqual([a.title for a in leaf.ancestors()], ["Root", "Mid"])


class NotebookAccessTests(TestCase):
    def setUp(self):
        self.c = ClientOrg.objects.create(name="Acme")
        self.pt = User.objects.create_user("pt", password="pw-123456789", role=Role.PENTESTER)
        self.other = User.objects.create_user("pt2", password="pw-123456789", role=Role.PENTESTER)
        self.aud = User.objects.create_user("aud", password="pw-123456789", role=Role.AUDITOR)
        self.eng = Engagement.objects.create(client=self.c, title="T", code="A-1")
        TeamAssignment.objects.create(user=self.pt, engagement=self.eng)
        self.page = Page.objects.create(engagement=self.eng, title="Notes",
                                        content="secret", created_by=self.pt)

    def test_member_creates_page(self):
        self.client.login(username="pt", password="pw-123456789")
        resp = self.client.post(reverse("notebook:create", args=[self.eng.code]), {
            "title": "Methodology", "content": "## Steps", "parent": "",
        })
        self.assertEqual(resp.status_code, 302)
        self.assertTrue(Page.objects.filter(title="Methodology").exists())

    def test_unassigned_pentester_blocked(self):
        self.client.login(username="pt2", password="pw-123456789")
        resp = self.client.get(reverse("notebook:page", args=[self.eng.code, self.page.slug]))
        self.assertEqual(resp.status_code, 403)

    def test_auditor_reads_but_cannot_edit(self):
        # Auditor sees all engagements (read) but cannot edit.
        self.client.login(username="aud", password="pw-123456789")
        self.assertEqual(
            self.client.get(reverse("notebook:page", args=[self.eng.code, self.page.slug])).status_code,
            200)
        self.assertEqual(
            self.client.get(reverse("notebook:create", args=[self.eng.code])).status_code,
            403)

    def test_preview_renders_sanitized(self):
        self.client.login(username="pt", password="pw-123456789")
        resp = self.client.post(reverse("notebook:preview", args=[self.eng.code]),
                                {"content": "# Hi <script>bad()</script>"})
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "<h1>")
        self.assertNotContains(resp, "<script>")

    def test_delete_cascades_children(self):
        child = Page.objects.create(engagement=self.eng, title="Child", parent=self.page)
        self.client.login(username="pt", password="pw-123456789")
        resp = self.client.post(reverse("notebook:delete", args=[self.eng.code, self.page.slug]))
        self.assertEqual(resp.status_code, 302)
        self.assertFalse(Page.objects.filter(pk=child.pk).exists())
