# Generated by Django 5.2.18 on 2026-10-06 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_key",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                (
                    "guidance",
                    models.TextField(
                        blank=True,
                        help_text="How to test / what to look for (copied into the test case notes).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("domain_key", "category", "order", "id"),
                "indexes": [
                    models.Index(
                        fields=["domain_key", "is_active"],
                        name="catalog_che_domain__d958d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "domain_key",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("network", "Network / Infrastructure"),
                            ("wifi", "Wi-Fi"),
                            ("ad", "Active Directory"),
                            ("desktop", "Desktop Application"),
                            ("atm", "ATM / XFS"),
                            ("api", "API"),
                            ("ai_agents", "AI Agents / LLM"),
                            ("ics_ot", "ICS / OT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="What this scenario tests, in one or two lines."
                    ),
                ),
                (
                    "steps",
                    models.TextField(
                        blank=True, help_text="Reproduction / testing steps."
                    ),
                ),
                (
                    "payloads",
                    models.TextField(
                        blank=True, help_text="Payloads, commands, or tooling."
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True, help_text="Links / CVEs / write-ups (one per line)."
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags, e.g. ssrf, cloud, idor",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("domain_key", "title"),
                "indexes": [
                    models.Index(
                        fields=["domain_key", "is_active"],
                        name="catalog_sce_domain__3bf7f3_idx",
                    )
                ],
            },
        ),
    ]
