# Generated by Django 5.2.18 on 2026-10-08 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bootstrap_checklists"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("checklist", "Checklist item"),
                            ("scenario", "Scenario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveIndex(
            model_name="checklistitem",
            name="catalog_che_domain__d958d1_idx",
        ),
        migrations.RemoveIndex(
            model_name="scenario",
            name="catalog_sce_domain__3bf7f3_idx",
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = global/shared; set = personal to this user.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_checklist_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = global/shared; set = personal to this user.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_scenarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(
                fields=["domain_key", "is_active", "owner"],
                name="catalog_che_domain__cf892d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(
                fields=["domain_key", "is_active", "owner"],
                name="catalog_sce_domain__5c9cc6_idx",
            ),
        ),
        migrations.AddField(
            model_name="contributionrequest",
            name="checklist_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contribution_requests",
                to="catalog.checklistitem",
            ),
        ),
        migrations.AddField(
            model_name="contributionrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contributionrequest",
            name="promoted_checklist_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.checklistitem",
            ),
        ),
        migrations.AddField(
            model_name="contributionrequest",
            name="promoted_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.scenario",
            ),
        ),
        migrations.AddField(
            model_name="contributionrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contribution_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contributionrequest",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contribution_requests",
                to="catalog.scenario",
            ),
        ),
    ]
